<?php if (!defined("APPLICATION")) {
    exit();
}
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration["Yaga"]["Reactions"]["Enabled"] = true; // Are reactions functional?
$Configuration["Yaga"]["Badges"]["Enabled"] = true; // Are badges functional?
$Configuration["Yaga"]["Ranks"]["Enabled"] = true; // Are ranks functional?

$Configuration["Preferences"]["Popup"]["BadgeAward"] = "1"; // Default Badge Award notifications to popup only
$Configuration["Preferences"]["Email"]["BadgeAward"] = "0";
$Configuration["Preferences"]["Popup"]["RankPromotion"] = "1"; // Default Rank Promotion notifications to popup and email
$Configuration["Preferences"]["Email"]["RankPromotion"] = "1";

// Defined module sort order for Yaga controllers
$Configuration["Modules"]["Yaga"]["Panel"] = [
    "MeModule",
    "UserBoxModule",
    "ActivityFilterModule",
    "UserPhotoModule",
    "ProfileFilterModule",
    "SideMenuModule",
    "UserInfoModule",
    "GuestModule",
    "Ads",
];
$Configuration["Modules"]["Yaga"]["Content"] = [
    "MessageModule",
    "MeModule",
    "UserBoxModule",
    "ProfileOptionsModule",
    "Notices",
    "ActivityFilterModule",
    "ProfileFilterModule",
    "BestFilterModule",
    "Content",
    "Ads",
];

$Configuration["Yaga"]["BestContent"]["PerPage"] = 10; // Per page limit on the best of page
$Configuration["Yaga"]["BestContent"]["Threshold"] = 5; // Minimum amount of points needed for display
$Configuration["Yaga"]["Ranks"]["Photo"] =
    "plugins/yaga/design/images/default_promotion.png"; // Default photo used for ranks activity items
$Configuration["Yaga"]["Badges"]["DefaultPhoto"] =
    "plugins/yaga/design/images/default_badge.png"; // Default photo used for badges pages
$Configuration["Yaga"]["Badges"]["RecentAwards"] = 15; // How many recent badge awards should be displayed
$Configuration["Yaga"]["Reactions"]["RecordLimit"] = 10; // The number of user avatars to show before collapsing them in the reaction record
$Configuration["Yaga"]["Profile"]["FullPagers"] = true; // Should full pagination be displayed in profile "best" pages?
$Configuration["Yaga"]["Dba"]["PointRecalculation"] = false; // Enable global point recalculation through dba/counts?
